#!/bin/bash
# 删除冗余文件

rm -f '/home/zmc/文档/programwork/scripts/train_terratnt_fixed.py'
rm -f '/home/zmc/文档/programwork/scripts/train_terratnt_optimized.py'
rm -f '/home/zmc/文档/programwork/scripts/train_terratnt_fas.py'
rm -f '/home/zmc/文档/programwork/scripts/train_terratnt_real_env.py'
rm -f '/home/zmc/文档/programwork/scripts/train_parallel.py'
rm -f '/home/zmc/文档/programwork/scripts/train_now.py'
rm -f '/home/zmc/文档/programwork/scripts/quick_train_baseline.py'
rm -f '/home/zmc/文档/programwork/scripts/train_single_model.py'
rm -f '/home/zmc/文档/programwork/scripts/visualize_results_fixed.py'
rm -f '/home/zmc/文档/programwork/scripts/draw_architecture.py'
rm -f '/home/zmc/文档/programwork/scripts/draw_architecture_fixed.py'
rm -f '/home/zmc/文档/programwork/scripts/draw_architecture_cn.py'
rm -f '/home/zmc/文档/programwork/scripts/draw_architecture_cn_fixed.py'
rm -f '/home/zmc/文档/programwork/scripts/draw_architecture_cn_v2.py'
rm -f '/home/zmc/文档/programwork/scripts/draw_architecture_en.py'
rm -f '/home/zmc/文档/programwork/scripts/download_new_regions.py'
rm -f '/home/zmc/文档/programwork/scripts/download_new_regions_no_proxy.py'
rm -f '/home/zmc/文档/programwork/scripts/direct_download_gee_data.py'
rm -f '/home/zmc/文档/programwork/scripts/gee_chunked_download.py'
rm -f '/home/zmc/文档/programwork/scripts/gee_tiled_download.py'
rm -f '/home/zmc/文档/programwork/scripts/gee_export_to_gcs.py'
rm -f '/home/zmc/文档/programwork/scripts/test_complete_pipeline.py'
rm -f '/home/zmc/文档/programwork/scripts/test_config_system.py'
rm -f '/home/zmc/文档/programwork/scripts/test_models.py'
rm -f '/home/zmc/文档/programwork/scripts/test_trajectory_generation.py'
rm -f '/home/zmc/文档/programwork/scripts/test_ui_fonts.py'
rm -f '/home/zmc/文档/programwork/CLEANUP_REPORT.md'
rm -f '/home/zmc/文档/programwork/PROGRESS_REPORT.md'
rm -f '/home/zmc/文档/programwork/PROJECT_STATUS.md'
rm -f '/home/zmc/文档/programwork/README_SYSTEM.md'
rm -rf '/home/zmc/文档/programwork/ui'
rm -rf '/home/zmc/文档/programwork/gui'
